# Generated by Django 6.0 on 2025-12-30 04:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_comment='ユーザー名', max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時', null=True)),
            ],
            options={
                'db_table': 'custom_user',
                'db_table_comment': 'カスタムユーザー',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
