# Generated by Django 6.0 on 2025-12-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matching_status',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Wating'), (3, 'Joined')], db_comment='状態', default=1),
        ),
    ]
