# Generated by Django 6.0 on 2025-12-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_matching_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matching_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Wating'), (2, 'Joined')], db_comment='状態', default=0),
        ),
    ]
