# Generated by Django 6.0 on 2026-09-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_matching_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='matching_status',
        ),
    ]
