# Generated by Django 6.0 on 2025-12-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時', null=True)),
                ('users', models.ManyToManyField(related_name='rooms', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserMatchingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'None'), (2, 'Wating'), (3, 'Joined')], db_comment='状態')),
                ('user', models.OneToOneField(db_comment='ユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='matching_status', to='accounts.customuser')),
            ],
        ),
    ]
