# Generated by Django 6.0 on 2025-12-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMatchingStatus',
        ),
    ]
